/**
 * OI-347: Local Storage Layer — Standalone Companion
 * Replaces API calls with chrome.storage.local for fully offline operation.
 * No account, no backend, no network required.
 */

export interface LocalProject {
  id: string;
  name: string;
  objective: string;
  phase: string;
  gates: Record<string, boolean>;
  conserved_scopes: string[];
  created_at: string;
  updated_at: string;
}

export interface LocalDecision {
  id: string;
  project_id: string;
  type: string;
  description: string;
  timestamp: string;
}

const STORAGE_KEYS = {
  PROJECTS: 'aixord_standalone_projects',
  DECISIONS: 'aixord_standalone_decisions',
  ACTIVE_PROJECT: 'aixord_standalone_active',
  DISMISSED_PROMPTS: 'aixord_standalone_dismissed',
} as const;

function generateId(): string {
  return crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2) + Date.now().toString(36);
}

async function getStorage<T>(key: string, fallback: T): Promise<T> {
  return new Promise((resolve) => {
    chrome.storage.local.get(key, (result) => {
      resolve(result[key] ?? fallback);
    });
  });
}

async function setStorage(key: string, value: unknown): Promise<void> {
  return new Promise((resolve) => {
    chrome.storage.local.set({ [key]: value }, resolve);
  });
}

// ─── Projects ───────────────────────────────────────────────────────────────

export async function listProjects(): Promise<LocalProject[]> {
  return getStorage<LocalProject[]>(STORAGE_KEYS.PROJECTS, []);
}

export async function getProject(id: string): Promise<LocalProject | null> {
  const projects = await listProjects();
  return projects.find(p => p.id === id) ?? null;
}

export async function createProject(name: string, objective: string): Promise<LocalProject> {
  const projects = await listProjects();
  const project: LocalProject = {
    id: generateId(),
    name,
    objective,
    phase: 'DISCOVER',
    gates: {},
    conserved_scopes: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
  projects.push(project);
  await setStorage(STORAGE_KEYS.PROJECTS, projects);
  await setStorage(STORAGE_KEYS.ACTIVE_PROJECT, project.id);
  return project;
}

export async function updateProject(id: string, updates: Partial<LocalProject>): Promise<void> {
  const projects = await listProjects();
  const idx = projects.findIndex(p => p.id === id);
  if (idx >= 0) {
    projects[idx] = { ...projects[idx], ...updates, updated_at: new Date().toISOString() };
    await setStorage(STORAGE_KEYS.PROJECTS, projects);
  }
}

export async function deleteProject(id: string): Promise<void> {
  const projects = await listProjects();
  await setStorage(STORAGE_KEYS.PROJECTS, projects.filter(p => p.id !== id));
}

export async function getActiveProjectId(): Promise<string | null> {
  return getStorage<string | null>(STORAGE_KEYS.ACTIVE_PROJECT, null);
}

export async function setActiveProject(id: string): Promise<void> {
  await setStorage(STORAGE_KEYS.ACTIVE_PROJECT, id);
}

// ─── Phase + Gates ──────────────────────────────────────────────────────────

export async function advancePhase(projectId: string, newPhase: string): Promise<void> {
  await updateProject(projectId, { phase: newPhase });
}

export async function toggleGate(projectId: string, gateId: string, value: boolean): Promise<void> {
  const project = await getProject(projectId);
  if (!project) return;
  const gates = { ...project.gates, [gateId]: value };
  await updateProject(projectId, { gates });
}

// ─── Decisions (OI-351) ─────────────────────────────────────────────────────

export async function listDecisions(projectId: string): Promise<LocalDecision[]> {
  const all = await getStorage<LocalDecision[]>(STORAGE_KEYS.DECISIONS, []);
  return all.filter(d => d.project_id === projectId);
}

export async function addDecision(projectId: string, type: string, description: string): Promise<LocalDecision> {
  const all = await getStorage<LocalDecision[]>(STORAGE_KEYS.DECISIONS, []);
  const decision: LocalDecision = {
    id: generateId(),
    project_id: projectId,
    type,
    description,
    timestamp: new Date().toISOString(),
  };
  all.push(decision);
  await setStorage(STORAGE_KEYS.DECISIONS, all);
  return decision;
}

// ─── Export (OI-352) ────────────────────────────────────────────────────────

export async function exportProjectReport(projectId: string): Promise<string> {
  const project = await getProject(projectId);
  if (!project) return '# No project found';

  const decisions = await listDecisions(projectId);
  const gateEntries = Object.entries(project.gates);
  const passed = gateEntries.filter(([, v]) => v).length;

  const lines = [
    `# ${project.name} — AIXORD Governance Report`,
    ``,
    `*Exported: ${new Date().toISOString()}*`,
    `*Generated by AIXORD Companion (Standalone)*`,
    ``,
    `## Project`,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Name | ${project.name} |`,
    `| Objective | ${project.objective} |`,
    `| Phase | ${project.phase} |`,
    `| Gates | ${passed}/${gateEntries.length} passed |`,
    `| Created | ${project.created_at} |`,
    ``,
    `## Gate Status`,
    `| Gate | Status |`,
    `|------|--------|`,
    ...gateEntries.map(([gate, status]) => `| ${gate} | ${status ? 'PASS' : 'PENDING'} |`),
    ``,
    `## Decision Ledger (${decisions.length} entries)`,
    `| Timestamp | Type | Decision |`,
    `|-----------|------|----------|`,
    ...decisions.map(d => `| ${d.timestamp} | ${d.type} | ${d.description} |`),
    ``,
    `---`,
    `*AIXORD Companion — Evidence over assertion. Structure over discipline.*`,
  ];

  return lines.join('\n');
}
